USE [master]
GO

/****** Object:  Database [DrugHouse]    Script Date: 22-11-2014 09:39:31 ******/
CREATE DATABASE [DrugHouse]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DrugHouse', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DrugHouse.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DrugHouse_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DrugHouse_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DrugHouse] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DrugHouse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DrugHouse] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DrugHouse] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DrugHouse] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DrugHouse] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DrugHouse] SET ARITHABORT OFF 
GO

ALTER DATABASE [DrugHouse] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DrugHouse] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DrugHouse] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DrugHouse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DrugHouse] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DrugHouse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DrugHouse] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DrugHouse] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DrugHouse] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DrugHouse] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DrugHouse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DrugHouse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DrugHouse] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DrugHouse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DrugHouse] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DrugHouse] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DrugHouse] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DrugHouse] SET RECOVERY FULL 
GO

ALTER DATABASE [DrugHouse] SET  MULTI_USER 
GO

ALTER DATABASE [DrugHouse] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DrugHouse] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DrugHouse] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DrugHouse] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DrugHouse] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DrugHouse] SET  READ_WRITE 
GO


